### ISSUE TITLE
Finalização do projeto

### ISSUE THREAD

**Issue by Werismitt** [Quenze/desafio-github-markdown#1]
Seria interessante fazer uma tabela na parte final do projeto, para sua finalização. O que colocar? Pensarei depois.

**Comment by Quenze** [comment]
É uma ótima ideia! Poderia fazer um pull request com as suas modificações para que eu possa incorporá-las?
Muito obrigada.

**Comment by Werismitt** [comment]
Claro! Assim que o fizer te avisarei.

**Comment by Quenze** [comment]
Obrigada!
